Q1) How many multiplications and additions do you need to perform a matrix multiplication between a (n, k) and (k, m) matrix? Explain.


Ans : To multiply the two matrix of (n,k) and (k,m) order, we need n*k*m multiplication and n*(m-1)*k addition.
We can clarify our answer more clearly, lets suppose x is the element in the position of a11 in the resultant answer of matrix after multiplication. x will be obtained and it requires k multiplications and k - 1 additions. This is because we are multiplying k elements from the row in first matrix with k elements from the column in second matrix and adding them together.

Q2) Write Python code to multiply the above two matrices. Solve using list of lists and then use numpy. Compare the timing of both solutions. Which one is faster? Why?

Ans : The code of the matrix multiplication using both the technique are written down

In [3]:
# Using lists of list
def matrix_multiplication_using_list(m,n):
    if len(m[0])!= len(n):
        print("Number of column and row of first and second matrix are not matching")
    answer =[[0 for _ in range(len(n[0]))] for _ in range(len(m))]
    for i in range(len(m)):
        for j in range(len(n[0])):
            for k in range(len(n)):
                answer[i][j]+=m[i][k]*n[k][j]
    return answer

matrix_m = [
    [1, 2],
    [3, 4],
    [5, 6]
]

matrix_n = [
    [7, 8, 9],
    [10, 11, 12]
]

result_lists = matrix_multiplication_using_list(matrix_m, matrix_n)
print("Matrix multiplication using lists of lists:")
for row in result_lists:
    print(row)

Matrix multiplication using lists of lists:
[27, 30, 33]
[61, 68, 75]
[95, 106, 117]


In [4]:
# Using numpy
import numpy as np

matrix_m = [
    [1, 2],
    [3, 4],
    [5, 6]
]

matrix_n = [
    [7, 8, 9],
    [10, 11, 12]
]

answer = np.dot(matrix_m,matrix_n)
print("Matrix Multiplication using numpy: ")
print(answer)

Matrix Multiplication using numpy: 
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


In [9]:
#comparing the time
def matrix_multiplication_using_list(m,n):
    if len(m[0])!= len(n):
        print("Number of column and row of first and second matrix are not matching")
    answer =[[0 for _ in range(len(n[0]))] for _ in range(len(m))]
    for i in range(len(m)):
        for j in range(len(n[0])):
            for k in range(len(n)):
                answer[i][j]+=m[i][k]*n[k][j]
    return answer

matrix_m = [
    [1, 2],
    [3, 4],
    [5, 6]
]

matrix_n = [
    [7, 8, 9],
    [10, 11, 12]
]

result_lists = matrix_multiplication_using_list(matrix_m, matrix_n)
print("Matrix multiplication using lists of lists:")
for row in result_lists:
    print(row)
import numpy as np

matrix_m = [
    [1, 2],
    [3, 4],
    [5, 6]
]

matrix_n = [
    [7, 8, 9],
    [10, 11, 12]
]

answer = np.dot(matrix_m,matrix_n)
print("Matrix Multiplication using numpy: ")
print(answer)
    
import timeit

time_taken_using_lists = timeit.timeit("matrix_multiplication_using_list(matrix_m, matrix_n)", globals=globals(), number=10000)

time_using_numpy = timeit.timeit("np.dot(matrix_m, matrix_n)", globals=globals(), number=10000)

print(f"Time taken for matrix multiplication using lists of lists: {time_taken_using_lists} seconds")
print(f"Time taken for matrix multiplication using NumPy: {time_using_numpy} seconds")

Matrix multiplication using lists of lists:
[27, 30, 33]
[61, 68, 75]
[95, 106, 117]
Matrix Multiplication using numpy: 
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]
Time taken for matrix multiplication using lists of lists: 0.19201820017769933 seconds
Time taken for matrix multiplication using NumPy: 0.12399300001561642 seconds


We have seen that matrix multiplication using a python library numpy takes less time than using list of list. This happended because Numpy utilizes optimized C and Fortran libraries which leads to faster execution due to vectorization and parrelization.

Q3) Finding the highest element in a list requires one pass of the array. Finding the second highest element requires 2 passes of the the array. Using this method, what is the time complexity of finding the median of the array? Can you suggest a better method? Can you implement both these methods in Python and compare against numpy.median routine in terms of time?
Ans : The time complexity to find the median of a list may take O(n^2) or higher. If we do sorting it will take O(nlogn) time.

In [10]:
#using multiple pass
def find_median_multiple_pass(arr):
    n = len(arr)
    if n % 2 == 0:
        k = n // 2
        for _ in range(k):
            max_value = max(arr)
            arr.remove(max_value)

        median = (max(arr) + max_value) / 2
    else:
        k = (n // 2) + 1
        for _ in range(k):
            median = max(arr)
            arr.remove(median)

    return median

# Example array
arr = [4, 2, 7, 1, 9, 5, 8, 3, 6]

# Finding median using multiple passes
median = find_median_multiple_pass(arr)
print("Median using multiple passes:", median)


Median using multiple passes: 5


In [12]:
# using sorting
def find_median_sorting(arr):
    sorted_arr = sorted(arr)
    n = len(sorted_arr)
    if n % 2 != 0:
        return sorted_arr[n // 2]
    else:
        mid = n // 2
        return (sorted_arr[mid - 1] + sorted_arr[mid]) / 2
    
arr = [4, 2, 7, 1, 9, 5, 8, 3, 6]

median = find_median_sorting(arr)
print("Median using Sorting:", median)

Median using Sorting: 5


In [13]:
#using numpy median
import numpy as np

arr = [4, 2, 7, 1, 9, 5, 8, 3, 6]
ans = np.median(arr)
print(ans)


5.0


In [17]:
import numpy as np
import timeit

def find_median_multiple_pass(arr):
    temp_arr = arr[:] 
    n = len(temp_arr)
    if n % 2 == 0:
        k = n // 2
        for _ in range(k):
            max_value = max(temp_arr)
            temp_arr.remove(max_value)

        median = (max(temp_arr) + max_value) / 2
    else:
        k = (n // 2) + 1
        for _ in range(k):
            median = max(temp_arr)
            temp_arr.remove(median)

    return median

def find_median_sorting(arr):
    sorted_arr = sorted(arr)
    n = len(sorted_arr)
    if n % 2 != 0:
        return sorted_arr[n // 2]
    else:
        mid = n // 2
        return (sorted_arr[mid - 1] + sorted_arr[mid]) / 2

arr = [4, 2, 7, 1, 9, 5, 8, 3, 6]

median_multiple_pass = find_median_multiple_pass(arr)
print("Median using Multiple Pass:", median_multiple_pass)

median_sorting = find_median_sorting(arr)
print("Median using Sorting:", median_sorting)

arr_np = np.array([4, 2, 7, 1, 9, 5, 8, 3, 6])
median_numpy = np.median(arr_np)
print("Median using NumPy:", median_numpy)

time_multiple_pass = timeit.timeit("find_median_multiple_pass(arr)", globals=globals(), number=1000)
time_sorting = timeit.timeit("find_median_sorting(arr)", globals=globals(), number=1000)
time_numpy = timeit.timeit("np.median(arr)", globals=globals(), number=1000)

print(f"Time taken for Method 1 (Multiple Pass): {time_multiple_pass} seconds")
print(f"Time taken for Method 2 (Sorting): {time_sorting} seconds")
print(f"Time taken for NumPy's median routine: {time_numpy} seconds")


Median using Multiple Pass: 5
Median using Sorting: 5
Median using NumPy: 5.0
Time taken for Method 1 (Multiple Pass): 0.007452700054273009 seconds
Time taken for Method 2 (Sorting): 0.0011395001783967018 seconds
Time taken for NumPy's median routine: 0.06440640008077025 seconds


given function: $$ f(x, y) = x^3y + y^3\sin(x) $$
\
partial derivative wiith respect to x: $$ \frac{\partial f}{\partial x} = 3x^2y + y^3\cos(x) $$
\
partial derivative with respect to y: $$ \frac{\partial f}{\partial y} = x^3 + 3y^2\sin(x) $$
\gradient vector is given by: $$ \nabla f = \left( \frac{\partial f}{\partial x}, \frac{\partial f}{\partial y} \right) = \left(3x^2y + y^3\cos(x), x^3 + 3y^2\sin(x)\right) $$


In [23]:
pip install jax jaxlib

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: C:\Users\KIIT\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip


In [24]:
#5. Use JAX to confirm the gradient evaluated by your method matches the analytical solution corresponding to a few random values of x and y
import jax
import jax.numpy as jnp

def f(x, y):
    return x**3 * y + y**3 * jnp.sin(x)

def analyticalGradient(x, y):
    df_dx = 3 * x**2 * y + y**3 * jnp.cos(x)
    df_dy = x**3 + 3 * y**2 * jnp.sin(x)
    return jnp.array([df_dx, df_dy])

gradF = jax.grad(f, argnums=(0, 1))

rng = jax.random.PRNGKey(0)
xValues = jax.random.uniform(rng, shape=(5,))
yValues = jax.random.uniform(rng, shape=(5,))

for x, y in zip(xValues, yValues):
    analyticalResult = analyticalGradient(x, y)
    jaxResult = gradF(x, y)

    print(f"Analytical Gradient: {analyticalResult}")
    print(f"JAX Computed Gradient: {jaxResult}")
    print(f"Match: {jnp.allclose(analyticalResult, jaxResult[0])}")
    print("\n")


Analytical Gradient: [0.72801733 0.7276784 ]
JAX Computed Gradient: (Array(0.72801733, dtype=float32), Array(0.7276784, dtype=float32))
Match: False


Analytical Gradient: [0.00395752 0.00395752]
JAX Computed Gradient: (Array(0.00395752, dtype=float32), Array(0.00395752, dtype=float32))
Match: True


Analytical Gradient: [0.23845413 0.23843008]
JAX Computed Gradient: (Array(0.23845413, dtype=float32), Array(0.23843008, dtype=float32))
Match: False


Analytical Gradient: [2.5925028 2.5851705]
JAX Computed Gradient: (Array(2.5925028, dtype=float32), Array(2.5851705, dtype=float32))
Match: False


Analytical Gradient: [0.8125792 0.8121386]
JAX Computed Gradient: (Array(0.8125792, dtype=float32), Array(0.8121386, dtype=float32))
Match: False


